initial_positions:
  # Left arm
  left_shoulder_pitch_joint_X6: 0.0
  left_shoulder_roll_joint_X6: 0.0
  left_shoulder_yaw_joint_X4: 0.0
  left_elbow_pitch_joint_X6: 0.0
  left_wrist_yaw_joint_X4: 0.0
  left_wrist_roll_joint_X4: 0.0
  # Right arm
  right_shoulder_pitch_joint_X6: 0.0
  right_shoulder_roll_joint_X6: 0.0
  right_shoulder_yaw_joint_X4: 0.0
  right_elbow_pitch_joint_X6: 0.0
  right_wrist_yaw_joint_X4: 0.0
  right_wrist_roll_joint_X4: 0.0
  # Left hand
  left_thumb_proximal_yaw_joint: 0.0
  left_thumb_proximal_pitch_joint: 0.0
  left_index_proximal_joint: 0.0
  left_middle_proximal_joint: 0.0
  left_ring_proximal_joint: 0.0
  left_pinky_proximal_joint: 0.0
  # Right hand
  right_thumb_proximal_yaw_joint: 0.0
  right_thumb_proximal_pitch_joint: 0.0
  right_index_proximal_joint: 0.0
  right_middle_proximal_joint: 0.0
  right_ring_proximal_joint: 0.0
  right_pinky_proximal_joint: 0.0
