# Configuration for Harambe with CoM + Posture controller
MainRobot: [json, "/home/alex/Documents/GitHub/ldr-harambe-arms-sim2real/src/control/mc_rtc_controller/config/harambe.json"]
Enabled: [HarambeCoMPosture]
IncludeHalfSitController: false
ControllerModulePaths: ["/home/alex/Documents/GitHub/ldr-harambe-arms-sim2real/src/control/mc_rtc_controller/build"]

ObserverPipelines:
- name: MainPipeline
  observers:
    - type: Encoder
      update: true
      log: true
      position: encoderValues
      velocity: encoderFiniteDifferences

# Logging
Log:
  Policy: threaded
  Directory: /tmp

# GUI Server
GUIServer:
  IPC: /tmp/mc_rtc_gui
  PUB: tcp://*:4252
  REP: tcp://*:4353
