# Default initial positions for arm_description's ros2_control fake system

initial_positions:
  shoulder_pitch_joint: 0.0
  shoulder_roll_joint: 0.0
  shoulder_yaw_joint: 0.0
  elbow_pitch_joint: 0.0
  elbow_yaw_joint: 0.0
  wrist_roll_joint: 0.0
  left_thumb_proximal_yaw_joint: 0.0
  left_thumb_proximal_pitch_joint: 0.0
  left_index_proximal_joint: 0.0
  left_middle_proximal_joint: 0.0
  left_ring_proximal_joint: 0.0
  left_pinky_proximal_joint: 0.0
