arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.2
  kinematics_solver_attempts: 5
  default_acceleration_scaling_factor: 1.0
  default_velocity_scaling_factor: 1.0
  position_only_ik: false
