# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pitch_joint
      - shoulder_roll_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - elbow_yaw_joint
      - wrist_roll_joint
    action_ns: follow_joint_trajectory
    default: true

  hand_controller:
    type: FollowJointTrajectory
    joints:
      - left_thumb_proximal_yaw_joint
      - left_thumb_proximal_pitch_joint
      - left_index_proximal_joint
      - left_middle_proximal_joint
      - left_ring_proximal_joint
      - left_pinky_proximal_joint
    action_ns: follow_joint_trajectory
    default: true
