controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - left_shoulder_pitch_joint_X6
        - left_shoulder_roll_joint_X6
        - left_shoulder_yaw_joint_X4
        - left_elbow_pitch_joint_X6
        - left_wrist_yaw_joint_X4
      gains:
        left_shoulder_pitch_joint_X6: {p: 100.0, d: 1.0}
        left_shoulder_roll_joint_X6: {p: 100.0, d: 1.0}
        left_shoulder_yaw_joint_X4: {p: 100.0, d: 1.0}
        left_elbow_pitch_joint_X6: {p: 50.0, d: 1.0}
        left_wrist_yaw_joint_X4: {p: 50.0, d: 1.0}
